app:
    resource: '@AppBundle/Controller/'
    type: annotation

#auth:
#    resource: "@AppBundle/Controller/Auth/"
#    type:     annotation

api:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation

#default:
#    path:     /
#    defaults: {_controller: AppBundle:Default:index}