security:

    encoders:
        Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
                entity:
                    class: AppBundle:User
                    property: email

        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$0G4FyrVuD.Yxw/ob804mr.e8dbUjMNelURrYmHbL.Thx4ok0IJMpS
                        roles: 'ROLE_ADMIN'
                    john:
                        password: $2y$12$1ht6JXh8CcXsscT0yqBZ4uwwAbdn6eyPGH9tLXj73SYS2bLeb5y3S
                        roles: 'ROLE_USER'
                    john1:
                        password: $2y$12$zgIZhlBxN0SP20cBS.8SfuyQ6uUpUDgtisI1m48h5VaydF63UEi9C
                        roles: 'ROLE_USER'

#        user_provider:
#                  entity:
#                      class:    AppBundle:User
#                      property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:

            pattern: ^/

            anonymous: true

            provider: database_users

            form_login:
                check_path: login
                login_path: login
                default_target_path: homepage
#                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   logout
                target: homepage

        api_auth:
            pattern:  ^/api/(registration|login)
            security: false
        api:
            pattern: ^/api/
            guard:
                authenticators:
                    - api.token_authenticator

        admin:
#            pattern: ^/admin
#            anonymous: ~
            security: true
            http_basic: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: '^/admin', roles: ROLE_ADMIN }