# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.token_authenticator:
                class: AppBundle\Security\TokenAuthenticator
                arguments: ['@doctrine.orm.entity_manager']

    app.user_manager:
                class: AppBundle\Manager\UserManager
                autowire: true
    app.expense_manager:
                class: AppBundle\Manager\ExpenseManager
                autowire: true