# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.token_authenticator:
                class: AppBundle\Security\TokenAuthenticator
                arguments: ['@doctrine.orm.entity_manager']

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.user_manager:
                class: AppBundle\Manager\UserManager
                autowire: true
    app.expense_manager:
                class: AppBundle\Manager\ExpenseManager
                autowire: true

    app.form_login_authenticator:
            class: AppBundle\Security\FormLoginAuthenticator
            arguments: ["@router", "@security.password_encoder"]